/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-30 09:41:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board.CrossFit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import vo.BoardVo;
import dao.BoardCfDao;
import vo.FileVo;

public final class ModifyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("vo.FileVo");
    _jspx_imports_classes.add("vo.BoardVo");
    _jspx_imports_classes.add("dao.BoardCfDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Cross Fit : Modify</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../assets/css/main.css\" />\r\n");
      out.write("</head>\r\n");

	String id = (String) session.getAttribute("id");
	if (id == null) {
		response.sendRedirect("../../member/signIn.jsp");
		return;
	}

	String pageNum = request.getParameter("pageNum");
	int num = Integer.parseInt(request.getParameter("num"));
	
	BoardCfDao boardCfDao = BoardCfDao.getInstance();
	
	BoardVo boardVo = boardCfDao.getAllInfosByNum(num);
	List<FileVo> fileList = boardVo.getFileList();


      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("\t<header id=\"header\" class=\"skel-layers-fixed\">\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t<a href=\"index.html\">WORKOUT</a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<a href=\"#nav\">Menu</a>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Nav -->\r\n");
      out.write("\t<nav id=\"nav\">\r\n");
      out.write("\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"generic.html\">Generic</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"board/CrossFit/BoardMain.jsp\">Cross Fit</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"../AerialYoga/BoardMain.jsp\">Aerial Yoga</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"../Pilates/BoardMain.jsp\">Pilates</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"links 3u 6u$(small) 12u$(xsmall)\">\r\n");
      out.write("\t\t");
 if(id !=null){ 
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"actions vertical small\">\r\n");
      out.write("\t\t\t\t<li><a href=\"MyPage.jsp\" class = \"button small\">My Page</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"../../member/signOut.jsp\" class=\"button special small\">Sign Out</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

		} else{
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"actions vertical small\">\r\n");
      out.write("\t\t\t\t<li><a href=\"../../member/signIn.jsp\" class=\"button special small\">Sign In</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"../../member/signUp.jsp\" class=\"button small\">Sign Up</a></li>\r\n");
      out.write("\t\t\t</ul>");

		}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"four\" class=\"wrapper style2 special\">\r\n");
      out.write("\t<h1>Cross Fit : Modify </h1>\r\n");
      out.write("\t<form action=\"ModifyPro.jsp\" method=\"post\" enctype=\"multipart/form-data\" name =\"frm\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"num\" value=\"");
      out.print(num );
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pageNum\" value=\"");
      out.print(pageNum );
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name= \"name\" value=\"");
      out.print(id );
      out.write("\">\r\n");
      out.write("\t<table id=\"notice\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"col\">Title</th>\r\n");
      out.write("\t\t\t<td style=\"text-align: left;\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"title\" value=\"");
      out.print(boardVo.getTitle() );
      out.write("\">\r\n");
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"col\">Files</th>\r\n");
      out.write("\t\t\t<td style=\"text-align: left;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"btnAddFile\">Add Files</button>\r\n");
      out.write("\t\t\t\t<div id=\"fileBox\">\r\n");
      out.write("\t\t\t\t\t<div id=\"oldFileBox\">\r\n");
      out.write("\t\t\t\t\t");
	
							for (FileVo fileVo : fileList) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"oldfile\" value=\"");
      out.print(fileVo.getUuid() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(fileVo.getFilename() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"delete-oldfile\">x</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"newFileBox\"></div>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"col\">Contents</th>\r\n");
      out.write("\t\t\t<td style=\"text-align: left;\">\r\n");
      out.write("\t\t\t\t<textarea rows=\"13\" cols=\"40\" name=\"content\">");
      out.print(boardVo.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"table_search\">\r\n");
      out.write("\t\t<button type=\"submit\">Modify</button>\r\n");
      out.write("\t\t<button type=\"reset\">ReWrite</button>\r\n");
      out.write("\t\t<button type=\"button\" onclick=\"location.href='BoardMain.jsp?pageNum=");
      out.print(pageNum );
      out.write("'\">Return</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"../../assets/jquery-3.5.1.js\"></script>\r\n");
      out.write("\t<script src=\"../../assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"../../assets/js/skel.min.js\"></script>\r\n");
      out.write("\t<script src=\"../../assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"../../assets/js/main.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar fileCnt = ");
      out.print(fileList.size() );
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('button#btnAddFile').click(function (event) {\r\n");
      out.write("\t\t\tif (fileCnt >= 3) {\r\n");
      out.write("\t\t\t\talert('No more add file');\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar str = '<div><input type=\"file\" name=\"filename\"><span class=\"delete-addfile\">x</span></div>';\r\n");
      out.write("\t\t\t$('div#newFileBox').append(str);\r\n");
      out.write("\t\t\tfileCnt++;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('div#newFileBox').on('click', 'span.delete-addfile', function (event) {\r\n");
      out.write("\t\t\t$(this).parent().remove(); // empty()는 안쪽요소만 비움\r\n");
      out.write("\t\t\tfileCnt--;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('span.delete-oldfile').click(function () {\r\n");
      out.write("\t\t\t$(this).parent().prev().prop('name', 'delfile');\r\n");
      out.write("\t\t\t$(this).parent().remove();\r\n");
      out.write("\t\t\tfileCnt--;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
