/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-07-23 03:46:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String id = (String) session.getAttribute("id");

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Retrospect by TEMPLATED</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<!--[if lte IE 8]><script src=\"assets/js/ie/html5shiv.js\"></script><![endif]-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"assets/css/ie8.css\" /><![endif]-->\r\n");
      out.write("<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"assets/css/ie9.css\" /><![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"landing\">\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<header id=\"header\" class=\"skel-layers-fixed\">\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t<a href=\"index.jsp\">WORKOUT</a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<a href=\"#nav\">Menu</a>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Nav -->\r\n");
      out.write("\t<nav id=\"nav\">\r\n");
      out.write("\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"board/CrossFit/BoardMain.jsp\">Cross Fit</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"links 3u 6u$(small) 12u$(xsmall)\">\r\n");
      out.write("\t\t");
 if(id !=null){ 

			if(id.equals("admin")){
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"actions vertical small\">\r\n");
      out.write("\t\t\t\t<li><a href=\"Management.jsp\" class = \"button small\">Manage</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"member/signOut.jsp\" class=\"button special small\">Sign Out</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");
 	
			}else{
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"actions vertical small\">\r\n");
      out.write("\t\t\t\t<li><a href=\"MyPage.jsp\" class = \"button small\">My Page</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"member/signOut.jsp\" class=\"button special small\">Sign Out</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
}
		} else{
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"actions vertical small\">\r\n");
      out.write("\t\t\t\t<li><a href=\"member/signIn.jsp\" class=\"button special small\">Sign In</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"member/signUp.jsp\" class=\"button small\">Sign Up</a></li>\r\n");
      out.write("\t\t\t</ul>");

		}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Banner -->\r\n");
      out.write("\t<section id=\"banner\">\r\n");
      out.write("\t\t<i class=\"icon fa-diamond\"></i>\r\n");
      out.write("\t\t<h2>JUST DO IT</h2>\r\n");
      out.write("\t\t<p>Magna feugiat lorem dolor egestas</p>\r\n");
      out.write("\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t<li><a href=\"#\" class=\"button big special\">Learn More</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- One -->\r\n");
      out.write("\t<section id=\"one\" class=\"wrapper style1\">\r\n");
      out.write("\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t<article class=\"feature left\">\r\n");
      out.write("\t\t\t\t<span class=\"image\"><img src=\"images/pic01.jpg\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2>Integer vitae libero acrisus egestas placerat sollicitudin</h2>\r\n");
      out.write("\t\t\t\t\t<p>Sed egestas, ante et vulputate volutpat, eros pede semper\r\n");
      out.write("\t\t\t\t\t\test, vitae luctus metus libero eu augue. Morbi purus libero,\r\n");
      out.write("\t\t\t\t\t\tfaucibus adipiscing, commodo quis, gravida id, est.</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button alt\">More</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t\t<article class=\"feature right\">\r\n");
      out.write("\t\t\t\t<span class=\"image\"><img src=\"images/pic02.jpg\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2>Integer vitae libero acrisus egestas placerat sollicitudin</h2>\r\n");
      out.write("\t\t\t\t\t<p>Sed egestas, ante et vulputate volutpat, eros pede semper\r\n");
      out.write("\t\t\t\t\t\test, vitae luctus metus libero eu augue. Morbi purus libero,\r\n");
      out.write("\t\t\t\t\t\tfaucibus adipiscing, commodo quis, gravida id, est.</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button alt\">More</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</article>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Two -->\r\n");
      out.write("\t<section id=\"two\" class=\"wrapper special\">\r\n");
      out.write("\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t<header class=\"major narrow\">\r\n");
      out.write("\t\t\t\t<h2>Aliquam Blandit Mauris</h2>\r\n");
      out.write("\t\t\t\t<p>Ipsum dolor tempus commodo turpis adipiscing Tempor placerat\r\n");
      out.write("\t\t\t\t\tsed amet accumsan</p>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<div class=\"image-grid\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic03.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic04.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic05.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic06.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic07.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic08.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic09.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"image\"><img src=\"images/pic10.jpg\" alt=\"\" /></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"button big alt\">Tempus Aliquam</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Three -->\r\n");
      out.write("\t<section id=\"three\" class=\"wrapper style3 special\">\r\n");
      out.write("\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t<header class=\"major narrow\t\">\r\n");
      out.write("\t\t\t\t<h2>Magna sed consequat tempus</h2>\r\n");
      out.write("\t\t\t\t<p>Ipsum dolor tempus commodo turpis adipiscing Tempor placerat\r\n");
      out.write("\t\t\t\t\tsed amet accumsan</p>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"button big alt\">Magna feugiat</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Four -->\r\n");
      out.write("\t<section id=\"four\" class=\"wrapper style2 special\">\r\n");
      out.write("\t\t<div class=\"inner\">\r\n");
      out.write("\t\t\t<header class=\"major narrow\">\r\n");
      out.write("\t\t\t\t<h2>Get in touch</h2>\r\n");
      out.write("\t\t\t\t<p>Ipsum dolor tempus commodo adipiscing</p>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<form action=\"#\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"container 75%\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row uniform 50%\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"6u 12u$(xsmall)\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"name\" placeholder=\"Name\" type=\"text\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"6u$ 12u$(xsmall)\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"email\" placeholder=\"Email\" type=\"email\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"12u$\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"message\" placeholder=\"Message\" rows=\"4\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t\t<li><input type=\"submit\" class=\"special\" value=\"Submit\" /></li>\r\n");
      out.write("\t\t\t\t\t<li><input type=\"reset\" class=\"alt\" value=\"Reset\" /></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/skel.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
