/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-07-13 00:34:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.format.DateTimeFormatter;
import dao.MemberDao;
import vo.MemberVo;
import dao.BoardCfDao;

public final class MyPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.MemberDao");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("vo.MemberVo");
    _jspx_imports_classes.add("dao.BoardCfDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");

	String id = (String) session.getAttribute("id");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Retrospect by TEMPLATED</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

	BoardCfDao dao = BoardCfDao.getInstance();
	MemberDao mDao = MemberDao.getInstance();
	MemberVo vo = mDao.getMemById(id);
	String dOrigin = vo.getRegDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
	String dCase1 =vo.getRegDate().plusMonths(1).minusDays(1).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
	String dCase2 = vo.getRegDate().plusMonths(3).minusDays(1).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
	String dCase3 =  vo.getRegDate().plusYears(1).minusDays(1).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
	String[] gx = vo.getGxType();

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Header -->\r\n");
      out.write("\t<header id=\"header\" class=\"skel-layers-fixed\">\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t<a href=\"index.html\">WORKOUT</a>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t\t<a href=\"#nav\">Menu</a>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Nav -->\r\n");
      out.write("\t<nav id=\"nav\">\r\n");
      out.write("\t\t<ul class=\"links\">\r\n");
      out.write("\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"generic.html\">Generic</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"board/CrossFit/BoardMain.jsp\">Cross Fit</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"links 3u 6u$(small) 12u$(xsmall)\">\r\n");
      out.write("\t\t");
 if(id !=null){ 
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"actions vertical small\">\r\n");
      out.write("\t\t\t\t<li><a href=\"MyPage.jsp\" class = \"button small\">My Page</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"member/signOut.jsp\" class=\"button special small\">Sign Out</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

		} else{
			
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"actions vertical small\">\r\n");
      out.write("\t\t\t\t<li><a href=\"member/signIn.jsp\" class=\"button special small\">Sign In</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"member/signUp.jsp\" class=\"button small\">Sign Up</a></li>\r\n");
      out.write("\t\t\t</ul>");

		}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"table-wrapper\">\r\n");
      out.write("\t\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t\t<h3>My Information</h3>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<th>회원 번호</th>\r\n");
      out.write("\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t<th>성별</th>\r\n");
      out.write("\t\t\t\t\t<th>등급</th>\r\n");
      out.write("\t\t\t\t\t<th>등록기간</th>\r\n");
      out.write("\t\t\t\t\t<th>등록 GX</th> \r\n");
      out.write("\t\t\t\t\t<th>연락처</th>\r\n");
      out.write("\t\t\t\t\t<th>주소</th>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(vo.getNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(vo.getId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(vo.getName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(vo.getGender());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");

							if (vo.getAuth() == 2) {
						
      out.write('강');
      out.write('사');

							} else if (vo.getAuth() == 3) {
						
      out.write('회');
      out.write('원');

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(dOrigin);
      out.write(' ');
      out.write('~');
      out.write(' ');

						if (vo.getPeriod().equals("1month")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(dCase1);

						} else if (vo.getPeriod().equals("3month")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(dCase2);

						} else if (vo.getPeriod().equals("1year")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(dCase3);

						}
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>");
System.out.println(vo.toString());
						for(String s : gx){
							System.out.println(s);
							
      out.print(s );
      out.write('/');

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(vo.getPhone() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(vo.getAddress() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"table-wrapper\">\r\n");
      out.write("\t\t<h3>Total Posts :</h3>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"button\" value=\"Withdrawal\" class=\"btn small\" onclick=\"location.href='member/WithdrawalPro.jsp'\">\r\n");
      out.write("\t<!-- footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts -->\r\n");
      out.write("\t<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/skel.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("\t<!--[if lte IE 8]><script src=\"assets/js/ie/respond.min.js\"></script><![endif]-->\r\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
