/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-07-01 06:29:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Welcome to Fun Web</title>\r\n");
      out.write("<link href=\"/css/default.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link href=\"/css/front.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link href=\"/css/print.css\" rel=\"stylesheet\" type=\"text/css\" media=\"print\">\r\n");
      out.write("<link href=\"/css/iphone.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/script/jquery-1.6.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/script/s3Slider.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() { \r\n");
      out.write("   $('#s3slider').s3Slider({ \r\n");
      out.write("      timeOut: 4000 \r\n");
      out.write("   });\r\n");
      out.write(" });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/top.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("    <div id=\"main_img\">\r\n");
      out.write("\t\t<!--  s3Slider -->\r\n");
      out.write("\t\t<div id=\"s3slider\">\r\n");
      out.write("\t\t\t<ul id=\"s3sliderContent\">\r\n");
      out.write("\t\t\t\t<li class=\"s3sliderImage\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/main_img.jpg\" width=\"971\" height=\"282\">\r\n");
      out.write("\t\t\t\t\t<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper erat est. <br>\r\n");
      out.write("\t\t\t\t\t\tAliquam metus elit, blandit eu luctus vitae, dictum sit amet mauris. Integer ut facilisis eros. <br>\r\n");
      out.write("\t\t\t\t\t\tDonec consectetur, velit id aliquam sagittis,</span>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"s3sliderImage\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/main_img1.jpg\" width=\"971\" height=\"282\">\r\n");
      out.write("\t\t\t\t\t<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper erat est. <br>\r\n");
      out.write("\t\t\t\t\t\tAliquam metus elit, blandit eu luctus vitae, dictum sit amet mauris. Integer ut facilisis eros. <br>\r\n");
      out.write("\t\t\t\t\t\tDonec consectetur, velit id aliquam sagittis,</span>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"s3sliderImage\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/images/main_img2.jpg\" width=\"971\" height=\"282\">\r\n");
      out.write("\t\t\t\t\t<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper erat est. <br>\r\n");
      out.write("\t\t\t\t\t\tAliquam metus elit, blandit eu luctus vitae, dictum sit amet mauris. Integer ut facilisis eros. <br>\r\n");
      out.write("\t\t\t\t\t\tDonec consectetur, velit id aliquam sagittis,</span>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<div class=\"clear s3sliderImage\"></div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--  s3Slider -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t<article id=\"front\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"solution\">\t\r\n");
      out.write("        <div id=\"hosting\">\r\n");
      out.write("            <h3>Web Hosting Solution</h3>\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc urna, \r\n");
      out.write("\t\t\t\tfringilla non fringilla ut, lacinia eu urna. Aliquam nec urna at nisi pulvinar eleifend. \r\n");
      out.write("\t\t\t\tDuis commodo luctus leo vitae feugiat. Curabitur ac sodales ante. Ut vel est </p>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        <div id=\"security\">\r\n");
      out.write("\t\t\t<h3>Web Security Solution</h3>\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc urna, \r\n");
      out.write("\t\t\t\tfringilla non fringilla ut, lacinia eu urna. Aliquam nec urna at nisi pulvinar eleifend. \r\n");
      out.write("\t\t\t\tDuis commodo luctus leo vitae feugiat. Curabitur ac sodales ante. Ut vel est </p>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        <div id=\"payment\">\r\n");
      out.write("\t\t\t<h3>Web payment Solution</h3>\r\n");
      out.write("\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nunc urna, \r\n");
      out.write("\t\t\t\tfringilla non fringilla ut, lacinia eu urna. Aliquam nec urna at nisi pulvinar eleifend. \r\n");
      out.write("\t\t\t\tDuis commodo luctus leo vitae feugiat. Curabitur ac sodales ante. Ut vel est </p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t<div id=\"sec_news\">\r\n");
      out.write("\t\t<h3><span class=\"orange\">Security</span> News</h3>\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt><a href=\"#\">Vivamus id ligula velit, quis euismod nisi</a></dt>\r\n");
      out.write("\t\t\t<dd><a href=\"#\">Proin quis ante eget arcu tempus tempus porta vel ipsum. \r\n");
      out.write("\t\t\t\t\tQuisque vitae nulla vel lorem cursus dignissim. Sed sit amet metus tortor. \r\n");
      out.write("\t\t\t\t\tIn hac habitasse platea dictumst. Aliquam erat volutpat. Aliquam massa risus, </a></dd>\r\n");
      out.write("\t\t\t<dt><a href=\"#\">Vivamus id ligula velit, quis euismod nisi</a></dt>\r\n");
      out.write("\t\t\t<dd><a href=\"#\">Proin quis ante eget arcu tempus tempus porta vel ipsum. \r\n");
      out.write("\t\t\t\t\tQuisque vitae nulla vel lorem cursus dignissim. Sed sit amet metus tortor. \r\n");
      out.write("\t\t\t\t\tIn hac habitasse platea dictumst. Aliquam erat volutpat. Aliquam massa risus, </a></dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"news_notice\">\r\n");
      out.write("\t\t<h3 class=\"brown\">News &amp; Notice</h3>\r\n");
      out.write("        <table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"contxt\"><a href=\"#\">Vivamus id ligula velit, quis euismod nisi </a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"#\">2011.07.31</a></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"contxt\">Fusce eros augue, tempus nec interdum eu</td>\r\n");
      out.write("\t\t\t\t<td>2011.06.11</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"contxt\">Donec eget tincidunt purus</td>\r\n");
      out.write("\t\t\t\t<td>2011.05.12</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"contxt\">Nam facilisis mauris in dui suscipit volutpat </td>\r\n");
      out.write("\t\t\t\t<td>2011.05.08</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"contxt\">Aenean in dui mollis leo ullamcorper fringilla </td>\r\n");
      out.write("\t\t\t\t<td>2011.04.25</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("        </table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("    </article>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
